# Generated by Django 5.1 on 2024-09-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodOrBadPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_or_bad', models.CharField(choices=[('good', 'ویژگی مثبت'), ('bad', 'ویژگی منفی')], default='good', max_length=50)),
                ('name', models.CharField(max_length=50, verbose_name='ویژگی مدنظر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نقطه قوت یا ضعف',
                'verbose_name_plural': 'نقاط قوت یا ضعف',
            },
        ),
    ]
